#ifndef INWALLCONSTANTS_H_INCLUDED
#define INWALLCONSTANTS_H_INCLUDED

#define KEUS_UART_MSG_INITIATOR 0x28
#define KEUS_UART_MSG_TERMINATOR 0x29
#define KEUS_UART_BUFFER 12

#define MAX_UART_DATA_BUFFER 10 //process buffer

#define INWALL_EVENTS(x) (1 << (x))

//Event bit masks
#define INWALL_BUTTON1 INWALL_EVENTS(0)
#define INWALL_BUTTON2 INWALL_EVENTS(1)
#define INWALL_BUTTON3 INWALL_EVENTS(2)
#define INWALL_BUTTON4 INWALL_EVENTS(3)
#define INWALL_BUTTON5 INWALL_EVENTS(4)
#define INWALL_BUTTON6 INWALL_EVENTS(5)
#define INWALL_BUTTON7 INWALL_EVENTS(6)
#define INWALL_BUTTON8 INWALL_EVENTS(7)
#define INWALL_BUTTON9 INWALL_EVENTS(8)
#define INWALL_BUTTON10 INWALL_EVENTS(9)
#define INWALL_BUTTON11 INWALL_EVENTS(10)
#define INWALL_BUTTON12 INWALL_EVENTS(11)
#define INWALL_BUTTON13 INWALL_EVENTS(12)
#define INWALL_BUTTON14 INWALL_EVENTS(13)
#define INWALL_BUTTON15 INWALL_EVENTS(14)
#define INWALL_BUTTON16 INWALL_EVENTS(15)
#define INWALL_BUTTON17 INWALL_EVENTS(16)

#define INWALL_UART INWALL_EVENTS(17)

#define INWALL_SLEEP_EVT INWALL_EVENTS(18)
#define INWALL_SPLASH_EVT INWALL_EVENTS(19)
#define INWALL_WATCHDOG_EVT INWALL_EVENTS(20)
//#define KEUS_RETRY_ACK 0X20
#define TASK_UART_ACK 5
#define SET_RGB 0XFF

#define SWITCH_ID1 0
#define SWITCH_ID2 1
#define SWITCH_ID3 2
#define SWITCH_ID4 3
#define SWITCH_ID5 4
#define SWITCH_ID6 5
#define SWITCH_ID7 6
#define SWITCH_ID8 7
#define SWITCH_ID9 8
#define SWITCH_ID10 9
#define SWITCH_ID11 10
#define SWITCH_ID12 11
#define SWITCH_ID13 12
#define SWITCH_ID14 13
#define SWITCH_ID15 14
#define SWITCH_ID16 15
#define SWITCH_ID17 16

#define MAX_NO_OF_SCENES 6
#define MAX_NO_OF_SWITCHES 6

#define RED 0
#define GREEN 1
#define BLUE 2

#define CONFIG_NORMAL 1
#define CONFIG_DIM 2
#define CONFIG_DALI 3
#define CONFIG_GROUP 4

#define MAX_NO_OF_DRIVERS 2

#define DRIVER_SLAVEID_1 0X3C
#define DRIVER_SLAVEID_2 0X3F

#define DRIVERID1 0
#define DRIVERID2 1
#define ALLDRIVERS 2

#define RGB_DRIVER_LEDS 24

#define INWALL_WAKE 1
#define INWALL_SLEEP 0

#define FAN_LEVEL_0 0
#define FAN_LEVEL_1 63
#define FAN_LEVEL_2 127
#define FAN_LEVEL_3 191
#define FAN_LEVEL_4 255

#define FAN_OPERATION_SET_LEDS 0
#define FAN_OPERATION_INC_LEVEL 1
#define FAN_OPERATION_DEC_LEVEL 2

#endif